#!/bin/bash

# Exit immediately on errors, and echo commands as they are executed.
set -ex

if [ -f "web/wp/wp-config.php" ]; then
  rm web/wp/wp-config.php
fi

if [ -d "web/wp/wp-content" ]; then
  rm -rf web/wp/wp-content
fi

if [ -d "content" ]; then
  rm -rf content
fi